/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.smartbracelet.sunny.sunnydemo2;

public final class Manifest {
    public static final class permission {
        public static final String MIPUSH_RECEIVE="com.smartbracelet.sunny.com.smartbracelet.sunny.sunnydemo2.sunnydemo2.permission.MIPUSH_RECEIVE";
    }
}
